  <footer>
    <div  class = "footer">
      <div>
        <h4>X</h4>
        <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
      </div>
      <section >
        <h4>Useful Links</h4>
        <ul class = "footerlink">
          <li><a href="#">Home</a></li>
          <li><a href="#">About us</a></li>
          <li><a href="#">Services</a></li>
          <li><a href="#">Terms of service</a></li>
          <li><a href="#">Privacy policy</a></li>
        </ul>
      </section>
      <section >
        <h4>Our Services</h4>
        <ul  class = "footerlink">
          <li><a href="#">Web Design</a></li>
          <li><a href="#">Marketing</a></li>
          <li><a href="#">Graphic Design</a></li>
        </ul>
      </section>
      <section >
        <h4>Contact Us</h4>
        <ul  class = "footerlink">
      <li ><a class="mail" href="mailto:103805253@student.swin.edu.au">Chi</a></li>
      <li><a class="mail" href="mailto:103805253@student.swin.edu.au">Thinh</a></li>
      <li><a class="mail" href="mailto:103805253@student.swin.edu.au">Long</a></li>
      <li ><a class="mail" href="mailto:103805253@student.swin.edu.au">Trang</a></li>
        </ul>
      </section>
    </div>
    <aside>&copy; Copyright <strong><span>X</span></strong>. All Rights Reserved</aside>
  </footer>