<header class="header">
  <nav>
    <img src="Images/logo.svg" alt="logo">
    <ul>
      <li><a href="index.php">Home</a></li>
      <li><a href="jobs.php">Job Descriptions</a></li>
      <li><a href="apply.php">Job Application</a></li>
      <li><a href="about.php">About Us</a>
        <div class="dropdown">
          <button class="dropbtn">
            <i class="fa-solid fa-bars"></i>
          </button>
          <div class="dropdown-content">
            <a href="index.php">Home</a>
            <a href="jobs.php">Job Descriptions</a>
            <a href="apply.php">Job Application</a>
            <a href="about.php">About Us</a>
          </div>
        </div>
      </li>
    </ul>
  </nav><!-- .navbar -->
</header><!-- End Header -->